export const GET_LIST_BANNER = "GET_LIST_BANNER"
export const GET_LIST_BANNER_SUCCESS = "GET_LIST_BANNER_SUCCESS"
export const GET_LIST_BANNER_FAIL = "GET_LIST_BANNER_FAIL"

export const POST_LIST_BANNER = "POST_LIST_BANNER"
export const POST_LIST_BANNER_SUCCESS = "POST_LIST_BANNER_SUCCESS"
export const POST_LIST_BANNER_FAIL = "POST_LIST_BANNER_FAIL"

export const DELETE_LIST_BANNER = "DELETE_LIST_BANNER"
export const DELETE_LIST_BANNER_SUCCESS = "DELETE_LIST_BANNER_SUCCESS"
export const DELETE_LIST_BANNER_FAIL = "DELETE_LIST_BANNER_FAIL"

export const UPDATE_LIST_BANNER = "UPDATE_LIST_BANNER"
export const UPDATE_LIST_BANNER_SUCCESS = "UPDATE_LIST_BANNER_SUCCESS"
export const UPDATE_LIST_BANNER_FAIL = "UPDATE_LIST_BANNER_FAIL"