export const GET_FACULTY_LIST = "GET_FACULTY_LIST"
export const GET_FACULTY_LIST_SUCCESS = "GET_FACULTY_LIST_SUCCESS"
export const GET_FACULTY_LIST_FAIL = "GET_FACULTY_LIST_FAIL"

export const POST_FACULTY_LIST = "POST_FACULTY_LIST"
export const POST_FACULTY_LIST_SUCCESS = "POST_FACULTY_LIST_SUCCESS"
export const POST_FACULTY_LIST_FAIL = "POST_FACULTY_LIST_FAIL"

export const GET_FILTER_FACULTY_LIST = "GET_FILTER_FACULTY_LIST"
export const GET_FILTER_FACULTY_LIST_SUCCESS = "GET_FILTER_FACULTY_LIST_SUCCESS"
export const GET_FILTER_FACULTY_LIST_FAIL = "GET_FILTER_FACULTY_LIST_FAIL"

export const DELETE_FACULTY_LIST = "DELETE_FACULTY_LIST"
export const DELETE_FACULTY_LIST_SUCCESS = "DELETE_FACULTY_LIST_SUCCESS"
export const DELETE_FACULTY_LIST_FAIL = "DELETE_FACULTY_LIST_FAIL"