export const GET_NEWS = "GET_NEWS"
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"
export const GET_NEWS_FAIL = "GET_NEWS_FAIL"

export const GET_NEWS_LATEST = "GET_NEWS_LATEST"
export const GET_NEWS_LATEST_SUCCESS = "GET_NEWS_LATESTSUCCESS"
export const GET_NEWS_LATEST_FAIL = "GET_NEWS_LATEST_FAIL"

export const FILTER_NEWS = "FILTER_NEWS"
export const FILTER_NEWS_SUCCESS = "FILTER_NEWS_SUCCESS"
export const FILTER_NEWS_FAIL = "FILTER_NEWS_FAIL"